[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[build]
ignoredPaths = [
  ".git",
  "*.md",
  ".gitignore",
  "temp.py",
  "final.py",
  "__pycache__",
  "*.pyc",
  ".vscode",
  ".idea"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT" 